name: Manually triggered workflow - first-action branch
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Sona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'Octoverse'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hi ${{ github.event.inputs.name }}!"
        echo "- in ${{ github.event.inputs.home }}!"
